name: Build

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - main
  pull_request:
    tags-ignore:
      - "v*"
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Cache or recover previous Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # Checking for errors with linter
      - name: Check for errors
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
      # Testing if the gradlew build succeed
      - name: Testing build
        run: ./gradlew build