name: Build

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - main
  pull_request:
    tags-ignore:
      - "v*"
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16', '17' ]
    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      # Install required JDK
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      # Testing if the gradlew build succeed
      - name: Testing build
        run: ./gradlew build