name: Publish to CurseForge

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      # Grab last Gradle cache
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # Build release with Gradle
      - name: Build with Gradle (Release)
        run: ./gradlew -Prelease.useLastTag=true final
      - id: getReleaseJar
        run: echo "::set-output name=file::$(ls build/libs/*[0-9].jar)"
      # Send release to CurseForge
      - name: Publish to CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 433692
          game_endpoint: minecraft
          file_path: ${{ steps.getReleaseJar.outputs.file }}
          changelog: Check the changelog on https://github.com/DevEkode/FabricLockette/releases
          game_versions: java:Java 8,minecraft-1-16:1.16.5,Fabric
          release_type: release