name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle (Release)
        if: ${{ !contains(github.ref,'rc') }}
        run: ./gradlew -Prelease.useLastTag=true final
      - name: Build with Gradle (PreRelease)
        if: contains(github.ref,'rc')
        run: ./gradlew -Prelease.useLastTag=true candidate
      - name: Package jar into artifact
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/libs