name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - 'ver/**'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16', '17' ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      # Install required JDK
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      # Build Release
      - name: Build with Gradle (Release)
        if: ${{ !contains(github.ref,'rc') }}
        run: ./gradlew -Prelease.useLastTag=true final
      # Build PreRelease
      - name: Build with Gradle (PreRelease)
        if: contains(github.ref,'rc')
        run: ./gradlew -Prelease.useLastTag=true candidate
      # Package artifact
      - name: Package jar into artifact
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/libs